### ISSUE TITLE
Save Changes Button Hidden on Wiki Edit

### ISSUE THREAD

**Issue by lvl4** [lvl4/lvl4#6]
<img width="947" alt="screen shot 2016-12-01 at 19 37 52" src="https://cloud.githubusercontent.com/assets/23053845/20792665/f5682976-b7fd-11e6-8b9a-f355c8a6f9e9.png">
"Save Changes" button still sometimes hidden.

**Comment by icetimux** [comment]
This only happens on small resolution screens, what resolution screen are you using?

**Comment by lvl4** [comment]
2560x1600 2013 MBP

**Comment by icetimux** [comment]
oh not small at all! could it be browser cache?

**Comment by lvl4** [comment]
Unlikely I'm afraid. Same effect on Chrome and Safari before and after clearing cache. Only on that wiki however.
<img width="983" alt="screen shot 2016-12-02 at 19 35 30" src="https://cloud.githubusercontent.com/assets/23053845/20832678/8eba842a-b8c6-11e6-8abd-939a3c13da04.png">

**Comment by icetimux** [comment]
I was able to reproduce the error and have since then fixed it and tested it, Are you zoomed in to the page?

**Comment by lvl4** [comment]
Not zoomed in, no. View is set to actual size. Interestingly enough, if I zoom out the error disappears.

**Comment by icetimux** [comment]
Thats pretty interesting, I will check and see if I can replicate and fix using a friend's MBP with the same resolution.
